#!/usr/bin/env python3
from __future__ import annotations

import argparse
import csv
from pathlib import Path


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Build training metadata table from audit reports."
    )
    parser.add_argument(
        "--file-audit-csv",
        type=Path,
        default=Path("ml/reports/audit/file_audit.csv"),
        help="Path to file_audit.csv generated by 01_audit_dataset.py",
    )
    parser.add_argument(
        "--subject-audit-csv",
        type=Path,
        default=Path("ml/reports/audit/subject_audit.csv"),
        help="Path to subject_audit.csv generated by 01_audit_dataset.py",
    )
    parser.add_argument(
        "--wav-root",
        type=Path,
        default=Path("ml/processed/wav_nsp"),
        help="Root directory where WAV files are/will be created.",
    )
    parser.add_argument(
        "--data-root",
        type=Path,
        default=Path("/Users/elifyildiz/Desktop/bitirme/data"),
        help="Original dataset root to map source path -> wav path.",
    )
    parser.add_argument(
        "--labels-csv",
        type=Path,
        default=None,
        help="Optional labels file with columns: subject_id,label",
    )
    parser.add_argument(
        "--modality",
        choices=("vowels", "sentences", "both"),
        default="vowels",
        help="Which modality rows to include.",
    )
    parser.add_argument(
        "--token-filter",
        default="",
        help='Optional comma list (e.g. "a_n,a_h"). Empty means all tokens.',
    )
    parser.add_argument(
        "--out-csv",
        type=Path,
        default=Path("ml/reports/metadata/training_metadata.csv"),
        help="Output metadata csv path.",
    )
    return parser.parse_args()


def read_subject_flags(subject_audit_csv: Path) -> dict[str, str]:
    flags: dict[str, str] = {}
    with subject_audit_csv.open("r", encoding="utf-8", newline="") as f:
        for row in csv.DictReader(f):
            flags[row["subject_id"]] = row.get("remarks_flags", "")
    return flags


def read_labels(labels_csv: Path | None) -> dict[str, str]:
    if labels_csv is None:
        return {}
    labels: dict[str, str] = {}
    with labels_csv.open("r", encoding="utf-8", newline="") as f:
        reader = csv.DictReader(f)
        required = {"subject_id", "label"}
        if not required.issubset(reader.fieldnames or set()):
            raise ValueError("labels_csv must include columns: subject_id,label")
        for row in reader:
            labels[row["subject_id"]] = row["label"]
    return labels


def should_exclude(remarks_flags: str, duration_sec: float) -> bool:
    # Conservative rule: hard-exclude clearly unusable signal or ultra-short clips.
    if "unusable_signal" in remarks_flags:
        return True
    if duration_sec < 0.25:
        return True
    return False


def main() -> None:
    args = parse_args()

    file_audit_csv = args.file_audit_csv.expanduser().resolve()
    subject_audit_csv = args.subject_audit_csv.expanduser().resolve()
    wav_root = args.wav_root.expanduser().resolve()
    data_root = args.data_root.expanduser().resolve()
    out_csv = args.out_csv.expanduser().resolve()
    out_csv.parent.mkdir(parents=True, exist_ok=True)

    token_filter = {
        token.strip() for token in args.token_filter.split(",") if token.strip()
    }
    labels = read_labels(args.labels_csv.expanduser().resolve() if args.labels_csv else None)
    subject_flags = read_subject_flags(subject_audit_csv)

    total_rows = 0
    written_rows = 0
    unlabeled_rows = 0

    with file_audit_csv.open("r", encoding="utf-8", newline="") as in_f, out_csv.open(
        "w", encoding="utf-8", newline=""
    ) as out_f:
        reader = csv.DictReader(in_f)
        writer = csv.DictWriter(
            out_f,
            fieldnames=[
                "subject_id",
                "label",
                "modality",
                "token",
                "source_path",
                "wav_path",
                "sample_rate_hz",
                "duration_sec",
                "remarks_flags",
                "quality_exclude",
            ],
        )
        writer.writeheader()

        for row in reader:
            total_rows += 1
            if row["ext"] != ".nsp":
                continue

            modality = row["modality"]
            if args.modality != "both" and modality != args.modality:
                continue

            token = row["token"]
            if token_filter and token not in token_filter:
                continue

            subject_id = row["subject_id"]
            label = labels.get(subject_id, "")
            if label == "":
                unlabeled_rows += 1

            source_path = Path(row["path"])
            rel = source_path.relative_to(data_root)
            wav_path = (wav_root / rel).with_suffix(".wav")

            duration_sec = float(row["duration_sec"])
            remarks_flags = subject_flags.get(subject_id, "")
            quality_exclude = should_exclude(remarks_flags, duration_sec)

            writer.writerow(
                {
                    "subject_id": subject_id,
                    "label": label,
                    "modality": modality,
                    "token": token,
                    "source_path": str(source_path),
                    "wav_path": str(wav_path),
                    "sample_rate_hz": row["sample_rate_hz"],
                    "duration_sec": row["duration_sec"],
                    "remarks_flags": remarks_flags,
                    "quality_exclude": quality_exclude,
                }
            )
            written_rows += 1

    print(f"[OK] Metadata CSV: {out_csv}")
    print(f"[INFO] Rows written: {written_rows}")
    print(f"[INFO] Rows without label: {unlabeled_rows}")
    print(f"[INFO] Source rows scanned: {total_rows}")


if __name__ == "__main__":
    main()
