#!/usr/bin/env python3
from __future__ import annotations

import argparse
import csv
import json
from collections import Counter
from pathlib import Path

import joblib
import numpy as np
from imblearn.over_sampling import SMOTE
from sklearn.ensemble import RandomForestClassifier


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Export the evaluated a_n+i_n speaker-split Random Forest model "
            "as a backend inference artifact."
        )
    )
    parser.add_argument(
        "--features-csv",
        type=Path,
        default=Path("ml/models/svd_a_n_i_n_speaker_split_run1/features_subject_level.csv"),
        help="Feature table generated by the speaker-split training pipeline.",
    )
    parser.add_argument(
        "--split-json",
        type=Path,
        default=Path("ml/models/svd_a_n_i_n_speaker_split_run1/split.json"),
        help="Speaker split JSON generated by the training pipeline.",
    )
    parser.add_argument(
        "--metrics-json",
        type=Path,
        default=Path("ml/models/svd_a_n_i_n_speaker_split_run1/metrics.json"),
        help="Metrics JSON for copying evaluation metadata into the artifact.",
    )
    parser.add_argument(
        "--target-dir",
        type=Path,
        default=Path("backend/model_artifacts/svd_a_n_i_n_v1"),
        help="Target directory for backend inference artifact files.",
    )
    parser.add_argument(
        "--seed",
        type=int,
        default=42,
        help="Random seed used for SMOTE and model fitting.",
    )
    parser.add_argument(
        "--rf-trees",
        type=int,
        default=300,
        help="Number of trees in the exported Random Forest model.",
    )
    return parser.parse_args()


def load_feature_table(
    features_csv: Path,
) -> tuple[np.ndarray, np.ndarray, np.ndarray, list[str]]:
    with features_csv.open("r", encoding="utf-8", newline="") as f:
        reader = csv.DictReader(f)
        if reader.fieldnames is None:
            raise SystemExit(f"Missing header in CSV: {features_csv}")

        feature_names = [
            name for name in reader.fieldnames if name not in ("subject_id", "label")
        ]
        rows = list(reader)

    if not rows:
        raise SystemExit(f"No rows found in features CSV: {features_csv}")

    x = np.array(
        [[float(row[name]) for name in feature_names] for row in rows],
        dtype=np.float64,
    )
    feature_fill_values = np.nanmean(np.where(np.isfinite(x), x, np.nan), axis=0)
    feature_fill_values = np.where(np.isfinite(feature_fill_values), feature_fill_values, 0.0)
    bad_mask = ~np.isfinite(x)
    if np.any(bad_mask):
        x[bad_mask] = np.take(feature_fill_values, np.where(bad_mask)[1])

    y = np.array([int(row["label"]) for row in rows], dtype=np.int64)
    subjects = np.array([str(row["subject_id"]) for row in rows], dtype=object)
    return x, y, subjects, feature_names


def apply_smote(x_train: np.ndarray, y_train: np.ndarray, seed: int) -> tuple[np.ndarray, np.ndarray]:
    minority_count = min(Counter(y_train.tolist()).values())
    k_neighbors = max(1, min(5, minority_count - 1))
    smote = SMOTE(random_state=seed, k_neighbors=k_neighbors)
    return smote.fit_resample(x_train, y_train)


def main() -> None:
    args = parse_args()
    features_csv = args.features_csv.expanduser().resolve()
    split_json = args.split_json.expanduser().resolve()
    metrics_json = args.metrics_json.expanduser().resolve()
    target_dir = args.target_dir.expanduser().resolve()
    target_dir.mkdir(parents=True, exist_ok=True)

    x, y, subjects, feature_names = load_feature_table(features_csv)
    split_payload = json.loads(split_json.read_text(encoding="utf-8"))
    metrics_payload = json.loads(metrics_json.read_text(encoding="utf-8"))

    train_subjects = {str(subject_id) for subject_id in split_payload["train_subjects"]}
    train_mask = np.isin(subjects, np.array(sorted(train_subjects), dtype=object))
    if not np.any(train_mask):
        raise SystemExit("No training subjects matched the feature table.")

    x_train = x[train_mask]
    y_train = y[train_mask]
    x_train_balanced, y_train_balanced = apply_smote(x_train, y_train, args.seed)

    model = RandomForestClassifier(
        n_estimators=args.rf_trees,
        random_state=args.seed,
        class_weight="balanced",
        n_jobs=-1,
    )
    model.fit(x_train_balanced, y_train_balanced)

    feature_fill_values = np.mean(x_train, axis=0)
    feature_mean = np.mean(x_train, axis=0)
    feature_std = np.std(x_train, axis=0)
    feature_std = np.where(feature_std < 1e-6, 1.0, feature_std)
    train_abs_z = np.abs((x_train - feature_mean) / feature_std)
    max_abs_zscore = np.max(train_abs_z, axis=1)
    mean_abs_zscore = np.mean(train_abs_z, axis=1)
    artifact_meta = {
        "artifact_version": "svd_a_n_i_n_v1",
        "model_type": "sklearn_random_forest",
        "model_name": "a_n_i_n_speaker_split_random_forest",
        "tokens": ["a_n", "i_n"],
        "preprocessing": {
            "target_sample_rate_hz": 50000,
            "trim_top_db": 35,
            "target_analysis_seconds": 2.0,
            "peak_normalization_target": 0.85,
        },
        "decision_policy": {
            "min_confidence_healthy": 0.6,
            "min_confidence_pathologic": 0.75,
            "max_abs_zscore_threshold": float(np.percentile(max_abs_zscore, 99)),
            "mean_abs_zscore_threshold": float(np.percentile(mean_abs_zscore, 99)),
        },
        "classes": {
            "0": "healthy",
            "1": "pathologic",
        },
        "feature_names": feature_names,
        "feature_fill_values": [float(value) for value in feature_fill_values.tolist()],
        "feature_mean": [float(value) for value in feature_mean.tolist()],
        "feature_std": [float(value) for value in feature_std.tolist()],
        "training": {
            "source_features_csv": str(features_csv),
            "source_split_json": str(split_json),
            "subjects_total": int(len(subjects)),
            "subjects_used_for_fit": int(np.sum(train_mask)),
            "seed": args.seed,
            "rf_trees": args.rf_trees,
            "smote_train_distribution": {
                str(label): int(count)
                for label, count in sorted(Counter(y_train_balanced.tolist()).items())
            },
        },
        "evaluation": metrics_payload.get("test_models", {}).get("random_forest", {}),
    }

    joblib.dump(model, target_dir / "model.joblib")
    (target_dir / "model_meta.json").write_text(
        json.dumps(artifact_meta, indent=2),
        encoding="utf-8",
    )
    (target_dir / "metrics.json").write_text(
        json.dumps(metrics_payload, indent=2),
        encoding="utf-8",
    )
    (target_dir / "split.json").write_text(
        json.dumps(split_payload, indent=2),
        encoding="utf-8",
    )

    bundle = {
        "model_type": artifact_meta["model_type"],
        "model_name": artifact_meta["model_name"],
        "tokens": artifact_meta["tokens"],
        "classes": artifact_meta["classes"],
        "artifact_files": {
            "model": str((target_dir / "model.joblib").resolve()),
            "meta": str((target_dir / "model_meta.json").resolve()),
            "metrics": str((target_dir / "metrics.json").resolve()),
            "split": str((target_dir / "split.json").resolve()),
        },
    }
    (target_dir / "inference_bundle.json").write_text(
        json.dumps(bundle, indent=2),
        encoding="utf-8",
    )

    print(f"[OK] Exported inference artifact to: {target_dir}")
    print(f"[INFO] Training subjects used: {int(np.sum(train_mask))}")
    print(
        "[INFO] Random Forest test metrics: "
        f"accuracy={artifact_meta['evaluation'].get('accuracy', 0.0):.4f} "
        f"f1={artifact_meta['evaluation'].get('f1_score', 0.0):.4f}"
    )


if __name__ == "__main__":
    main()
