name: mobile
description: Voice Therapy App mobile client.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  record: ^6.2.0
  path_provider: ^2.1.4
  path: ^1.9.0
  http: ^1.2.2
  sqflite: ^2.3.3+1
  crypto: ^3.0.6
  video_player: ^2.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/branding/
    - assets/videos/vocal_function/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/branding/background.png"
  min_sdk_android: 21
  adaptive_icon_background: "#2F5D50"
  adaptive_icon_foreground: "assets/branding/vocalflow_icon.png"
